version: '2'
services:
  spark-worker-1:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://${SPARK_MASTER_HOST}:7077
    container_name: spark-worker-1
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8088
      - 8081
    ports:
      - 8088:8088
      - 8081:8081
    environment:
      - SPARK_CONF_DIR=/conf
      - SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORE}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
      - SPARK_PUBLIC_DNS=localhost
    volumes:
      - ./mount/spark-worker-1/conf:/conf
      - ./mount/spark-worker-1/data:/tmp/data

    networks:
      - spark-net
      
networks:
  spark-net:
    external:
      name: spark-net
